[colors]
draw_bold_text_with_bright_colors = true
    [colors.primary]
	background = '#0f0f0f'

[cursor.style]
blinking = "On"
shape = "Block"

[font]
size = 10.5

[font.normal]
family = "FiraMono Nerd Font"
style = "Medium"

[shell]
program = "/bin/zsh"

[window]
opacity = 0.90

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.dimensions]
columns = 100
lines = 27

[window.padding]
x = 2
y = 2

[window.position]
x = 100
y = 100
